#!/bin/bash -e

self_dir=$(dirname $0)
dump_file=hgdump.$$
supp_file=$self_dir/valgrind.supp

echo "-- writing dump to $dump_file"

valgrind --tool=helgrind \
    --demangle=no \
    --num-callers=20 \
    --log-file=$dump_file \
    --suppressions=$supp_file \
    $*
